import urllib.request
import bs4
import feedparser
from pydantic import BaseModel, Field

from ..core import console
from .brain import (
    IntentEngine,
    ContextResolver,
    ReasoningEngine,
    ShouldIReplyEngine,
    ConfidenceScorer,
    DecisionEngine,
    Decision,
)
from .nlp import (
    Tokenizer,
    SpellCorrector,
    EntityExtractor,
    SentimentAnalyzer,
    TopicExtractor,
)
from .memory import (
    ChatMessage,
    ShortTermMemory,
    LongTermMemory,
    UserMemoryManager,
    GroupMemoryManager,
)
from .knowledge import (
    FactDatabase,
    SQLiteStatementDatabase,
    KnowledgeIndex,
    KnowledgeGraph,
)
from .learning import (
    ContinuousLearner,
    FeedbackProcessor,
    GroupVocabulary,
)
from .response import (
    ResponseGenerator,
    HumorEngine,
)


class BotResponse(BaseModel):
    """Output response structure generated by StrictNLPBot."""

    should_reply: bool = True
    relevance_score: float = 100.0
    reply_text: str = ""
    response_mode: str = "RESPOND"
    intent: str = "general_chat"
    confidence: float = 1.0
    source_module: str = "nlp_engine"
    topic: str = "general"


class StrictNLPBot:
    """
    Modular 3-Tier Layered Brain Architecture with ChatterBot-style SQLite Statement Memory:
    - LEVEL 1: FAST (<10ms) -> Mention, command, spam, fast scoring guard.
    - LEVEL 2: SMART         -> Context, entities, sentiment, topic, user profile, ChatterBot SQLite pair trainer.
    - LEVEL 3: DEEP          -> ChatterBot SQLite lookup, knowledge search, graph traversal, response ranking.
    """

    def __init__(self):
        console.status("INIT", "Initializing 3-Tier Layered Brain Architecture...")

        # Core Memory & Per-Group / Per-User Stores
        self.long_term_memory = LongTermMemory()
        self.short_term_memory = ShortTermMemory()
        self.user_memory = UserMemoryManager(self.long_term_memory)
        self.group_memory = GroupMemoryManager(self.long_term_memory)

        # Level 1 & Level 2 NLP Pipeline
        self.tokenizer = Tokenizer()
        self.spell_corrector = SpellCorrector(vocabulary_size=5000)
        self.entity_extractor = EntityExtractor()
        self.sentiment_analyzer = SentimentAnalyzer()
        self.topic_extractor = TopicExtractor()

        # Level 3 Knowledge, Graph, & ChatterBot SQLite Database
        self.fact_db = FactDatabase(self.long_term_memory)
        self.statement_db = SQLiteStatementDatabase()
        self.kb = KnowledgeIndex()
        self.graph = KnowledgeGraph()

        # Brain Engines & Decisioning
        self.intent_engine = IntentEngine()
        self.context_resolver = ContextResolver()
        self.reasoning_engine = ReasoningEngine()
        self.should_reply_engine = ShouldIReplyEngine()
        self.confidence_scorer = ConfidenceScorer()
        self.decision_engine = DecisionEngine()

        # Learning & Feedback
        self.learner = ContinuousLearner(self.fact_db)
        self.feedback = FeedbackProcessor(self.fact_db)
        self.vocabulary = GroupVocabulary()

        # Response Engine
        self.humor = HumorEngine()
        self.response_generator = ResponseGenerator(self.humor)

        console.success("3-Tier Layered Brain Architecture Active!")

    def process_message(self, message: ChatMessage) -> BotResponse:
        """Execute 3-Tier Layered Brain Processing."""

        # ----------------------------------------------------------------------
        # LEVEL 1: FAST PROCESSING (<10ms)
        # ----------------------------------------------------------------------
        self.short_term_memory.add(message)
        intent, confidence = self.intent_engine.detect(message.text)
        entities = self.entity_extractor.extract(message.text)

        should_reply, score, mode_str = self.should_reply_engine.evaluate(
            message, entities, self.group_memory.topic_state
        )

        decision = self.decision_engine.decide_mode(should_reply, score, intent)

        # ----------------------------------------------------------------------
        # LEVEL 2: SMART PROCESSING & CONTINUOUS LEARNING (EVERY MESSAGE)
        # ----------------------------------------------------------------------
        prof = self.user_memory.get_profile(message.user_id, message.user_name)
        prof.total_messages += 1
        prof.avg_msg_length = round(
            (prof.avg_msg_length * (prof.total_messages - 1) + len(message.text)) / prof.total_messages, 1
        )

        corrected_text = self.spell_corrector.correct(message.text)
        tokens, lemmas = self.tokenizer.tokenize_and_lemmatize(corrected_text)
        key_words = self.topic_extractor.extract_keywords(lemmas)

        target_subject = self.reasoning_engine.reason_about_message(message.text, intent, entities)
        self.group_memory.update_topic(target_subject, message.user_name)

        # Continuous Learning & Knowledge Graph Updates on EVERY message
        for kw, _ in key_words:
            self.graph.add_fact(message.user_name, "discussed", kw)
            prof.favorite_topics[kw] = prof.favorite_topics.get(kw, 0) + 1

        self.user_memory.save_profile(prof)
        self.learner.learn_from_message(message.user_name, message.text)

        # ChatterBot Statement Pair SQLite Learning from sequential group messages
        recent_history = self.short_term_memory.get_recent(count=2)
        if len(recent_history) >= 2:
            prev_msg = recent_history[-2]
            if prev_msg.user_id != message.user_id:
                self.statement_db.learn_pair(prev_msg.text, message.text, user_id=message.user_id)

        # ----------------------------------------------------------------------
        # LEVEL 1: DECISION GUARD (SHOULD BOT REPLY?)
        # ----------------------------------------------------------------------
        if decision == Decision.SILENCE:
            return BotResponse(
                should_reply=False,
                relevance_score=score,
                reply_text="",
                response_mode="SILENCE",
                intent=intent,
            )

        # ----------------------------------------------------------------------
        # LEVEL 3: DEEP PROCESSING & CANDIDATE RESPONSE SELECTION
        # ----------------------------------------------------------------------
        reply_text = ""
        source_module = "nlp_engine"

        lower_raw = message.text.lower().strip()
        if lower_raw.startswith(("http://", "https://", "/scrape ")):
            url = lower_raw.replace("/scrape ", "").strip()
            if "rss" in url or "feed" in url:
                feed = feedparser.parse(url)
                titles = [e.get("title", "") for e in feed.entries[:3]]
                reply_text = f"📰 Feed Headlines from '{url}':\n" + "\n".join([f"• {t}" for t in titles])
                source_module = "feedparser"
            else:
                try:
                    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                    with urllib.request.urlopen(req, timeout=5) as resp:
                        soup = bs4.BeautifulSoup(resp.read().decode("utf-8", errors="ignore"), "html.parser")
                        text_snip = " ".join(soup.get_text().split()[:100])
                    reply_text = f"🌐 Web Scraped: {soup.title.string if soup.title else url}\n{text_snip}"
                except Exception as exc:
                    reply_text = f"Failed to fetch webpage: {exc}"
                source_module = "bs4_scraper"

        if not reply_text:
            context_reply = self.context_resolver.resolve_implicit_context(
                message.text, self.short_term_memory.get_recent(count=3)
            )
            if context_reply:
                reply_text = context_reply
                source_module = "context_resolver"

        # Check ChatterBot SQLite Statement DB for learned conversational pair
        if not reply_text:
            learned_stmt = self.statement_db.find_best_response(message.text)
            if learned_stmt:
                reply_text = learned_stmt
                source_module = "sqlite_chatterbot_memory"

        if not reply_text:
            reply_text, source_module = self.response_generator.generate(
                message, intent, entities, self.short_term_memory.get_recent(count=3)
            )

        return BotResponse(
            should_reply=True,
            relevance_score=score,
            reply_text=reply_text,
            response_mode=decision.value,
            intent=intent,
            confidence=confidence,
            source_module=source_module,
            topic=self.group_memory.topic_state.current_topic,
        )
