"""Consolidated Chatbot Feature Engine."""
import time
import random
from collections import deque
from dataclasses import dataclass, field
from typing import List, Optional

from ...app import console

@dataclass
class ChatMessage:
    """Incoming & Outgoing chat message data model."""
    text: str
    message_id: str = field(default_factory=lambda: str(int(time.time() * 1000)))
    thread_id: str = "global_thread"
    user_id: str = "user_default"
    user_name: str = "User"
    timestamp: float = field(default_factory=time.time)
    reply_to_user_id: Optional[str] = None
    replied_to_text: Optional[str] = None
    is_bot_mentioned: bool = False

@dataclass
class BotResponse:
    """Output response structure generated by StrictNLPBot."""
    should_reply: bool = True
    relevance_score: float = 100.0
    reply_text: str = ""
    response_mode: str = "RESPOND"
    intent: str = "general_chat"
    confidence: float = 1.0
    source_module: str = "chatbot"
    topic: str = "general"

COMMON_RESPONSES = [
    "Haan bhai bolo, kya haal chaal?",
    "Bas mast chal raha hai, tu bata!",
    "Toh jaakar bartan dho le, boredom gayab ho jayega! 🧹",
    "Ja so ja, sapne mein bhi bakchodi mat karna! 😴",
    "Bhai dono hi pagal hain tabhi toh late night group chat kar rahe hain 😂",
    "Aaj subha 😮‍💨",
    "Neend udegaye!",
]

class StrictNLPBot:
    """Consolidated Chatbot engine with short term memory and fast response matching."""

    def __init__(self, storage=None):
        console.status("INIT", "Initializing Chatbot Engine...")
        self.storage = storage
        self.history: deque[ChatMessage] = deque(maxlen=50)
        console.success("Chatbot Engine Active!")

    def process_message(self, message: ChatMessage) -> BotResponse:
        """Process incoming chat message and return BotResponse."""
        self.history.append(message)
        text_lower = message.text.lower().strip()

        # Check if bot was mentioned or direct question
        if message.is_bot_mentioned or "nexus" in text_lower or "oli" in text_lower:
            reply = random.choice(COMMON_RESPONSES)
            return BotResponse(
                should_reply=True,
                relevance_score=100.0,
                reply_text=reply,
                response_mode="RESPOND",
                intent="direct_chat",
                source_module="chatbot"
            )

        # Default fallback
        return BotResponse(
            should_reply=False,
            relevance_score=0.0,
            reply_text="",
            response_mode="SILENCE",
            intent="idle",
            source_module="chatbot"
        )
