"""Help command generator."""

def generate_help_text(prefix: str = "oli") -> str:
    return (
        "🤖 OLI BOT COMMANDS MENU 🤖\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        f"💡 {prefix} help - Show this commands menu\n"
        f"💡 {prefix} hi / hello - Friendly greeting\n"
        f"💡 {prefix} ping - Check bot responsiveness\n"
        f"💡 {prefix} rules - Display group rules\n"
        f"💡 {prefix} react <emoji> - React to last message\n"
        "\n"
        "🧠 AI & NLP CHATBOT:\n"
        f"💬 {prefix} chat <msg> - Talk with AI ChatBot\n"
        f"💬 {prefix} feed <url> - Parse live RSS news feed\n"
        f"💬 {prefix} scrape <url> - Web page lookup & index\n"
        f"💬 {prefix} graph [topic] - View concept knowledge graph\n"
        f"💬 {prefix} kb <query> - Search Whoosh knowledge base\n"
        "\n"
        "🎯 TRUTH & DARE GAME:\n"
        f"🍾 {prefix} tdgame @user1 @user2 - Create T&D lobby\n"
        f"🍾 {prefix} tdstart / {prefix} tdnext - Spin bottle for next player\n"
        f"🍾 {prefix} truth / {prefix} dare - Pick truth question or dare task\n"
        f"🍾 {prefix} tdstop - End active T&D game\n"
        "\n"
        "🔍 INSTAGRAM LOOKUP:\n"
        f"🔎 {prefix} know @user - Fetch public profile details\n"
        "\n"
        "🎲 FUN & ENTERTAINMENT:\n"
        f"💡 {prefix} advice - Get random advice\n"
        f"💡 {prefix} joke - Tell a funny joke\n"
        f"💡 {prefix} fact - Share an interesting fact\n"
        f"💡 {prefix} recipe / meal - Discover a random recipe\n"
        f"💡 {prefix} bored - Find an activity\n"
        f"💡 {prefix} yesno <question> - Ask the oracle\n"
        "\n"
        "💰 ECONOMY & SHOP:\n"
        f"🪙 {prefix} daily - Claim 100 free coins daily\n"
        f"🪙 {prefix} balance - Check your XP, level & coins\n"
        f"🪙 {prefix} shop - View titles & badges shop\n"
        f"🪙 {prefix} buy <id> - Purchase shop items\n"
        f"🪙 {prefix} gift @user <amount> - Transfer coins\n"
        f"🏆 {prefix} top - View group leaderboard\n"
        "\n"
        "📢 GROUP REVIVAL & CONTROLS:\n"
        f"⏰ Group jaago / {prefix} jaago - Mention active members\n"
        f"⚙️ {prefix} status - View bot status & uptime\n"
        f"⚙️ {prefix} report - Alert group admins\n"
        f"⚙️ {prefix} ghosts [days] - Find silent members\n"
        f"⚙️ {prefix} gc info - Display group metadata\n"
        f"⚙️ {prefix} gc add <username> - Add member to group\n"
        f"⚙️ {prefix} faq set <key> | <reply> - Add auto-reply\n"
        f"⚙️ {prefix} faq remove <key> - Delete auto-reply\n"
        "\n"
        "🛡️ MODERATION & WARNINGS:\n"
        f"⚠️ {prefix} warn @user [reason] - Warn a member\n"
        f"⚠️ {prefix} warnings @user - Check user warnings\n"
        f"⚠️ {prefix} warnadd <word> - Add forbidden word\n"
        f"⚠️ {prefix} warnremove <word> - Remove forbidden word\n"
        f"⚠️ {prefix} warnlist - List active forbidden words"
    )
